### ISSUE TITLE
DL: overview assignment

### ISSUE THREAD

**Issue by zhangqi444** [ocademy-ai/machine-learning#208]

**Comment by WHQWHQWHQ** [comment]
https://www.kaggle.com/datasets/russellyates88/suicide-rates-overview-1985-to-2016

**Comment by bestfw** [comment]
https://www.tensorflow.org/tutorials/quickstart/beginner
https://www.tensorflow.org/tutorials/keras/classification

license：https://github.com/tensorflow/docs
