### ISSUE TITLE
DL: DQN assignment

### ISSUE THREAD

**Issue by zhangqi444** [ocademy-ai/machine-learning#215]

**Comment by MorganeLu** [comment]
https://www.kaggle.com/code/phunghieu/connectx-with-deep-q-learning

**Comment by WHQWHQWHQ** [comment]
https://www.kaggle.com/code/anmolkapoor/rps-rl-using-deep-q-network-dqn

**Comment by WHQWHQWHQ** [comment]
https://www.kaggle.com/code/emrebulbul23/dqn-on-foreign-exchange-market

**Comment by HarryandJack** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月15日(星期六) 晚上10:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ocademy-ai/machine-learning] DL: DQN assignment (Issue #215)





 
https://www.kaggle.com/code/emrebulbul23/dqn-on-foreign-exchange-market
